
name: Run input & output test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:  
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Setup Node 
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: cd src/ && node index.js &

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: start live server # Start a live-server for testing the webpage content
      run: |
        cd src/html/
    - name: Run Tests scripts on localhost
      run: python tests/test.py http://localhost:8000/
